# Quiz2
Open the file "numbers.txt" as ```f```.

Create a string variable called ```text``` and initialize with text in the file.<br>
After that, split the text with comma, and name it splitted.

Release the access of file.

Create a list called ```numbers``` and initialize with empty list.

Write a for-loop which enumerates strings in the ```splitted``` and convert each element to float, and then push that value to the end of the ```numbers```.

Print the content and the type of the first element in the numbers.

It should be...
>3.21<br>
><class 'float'>

Import numpy as np.

Convert numbers to numpy-array and store that array with name ```numarray```

Import matplotlib.pyplot as plt

Create a figure whose size is 8 in width and 4 in height.<br>
Create an single axis inside figure.<br>
Draw line-graph about numarray to the axis.<br>
Set the label of x-axis to "time[ms]".<br>
Set the label of y-axis to "voltage[mV]".<br>
Set the title of axis to "Changes of Voltage".<br>
Finally, show the graph.

Print the length of ```numarray```. It must be 500.

Create a roi called ```sub0``` which contains from ```numarray[0]``` until ```numarray[495]```.<br>
Print the length of ```sub0```, it must be 496.

Create a roi called ```sub1``` which contains from ```numarray[1]``` until ```numarray[496]```.<br>
Print the length of ```sub1```, it must be 496.

Create a roi called ```sub2``` which contains from ```numarray[2]``` until ```numarray[497]```.<br>
Create a roi called ```sub2``` which contains from ```numarray[3]``` until ```numarray[498]```.<br>
Create a roi called ```sub2``` which contains from ```numarray[4]``` until ```numarray[499]```.<br>
Print the length of them. All the length must be 496.

Print the first 10 elements in numarray. This can be write like ```print(numarray[:10])```<br>
Similarly, write the program that shows first 6 elements in ```sub0```, ```sub1```, ```sub2```, ```sub3```, and ```sub4```.

It must be like <br>
>[ 3.21  5.33  0.46  7.87 21.93 10.1  11.85  9.12  6.17 -0.43]<br>
>[ 3.21  5.33  0.46  7.87 21.93 10.1 ]<br>
>[ 5.33  0.46  7.87 21.93 10.1  11.85]<br>
>[ 0.46  7.87 21.93 10.1  11.85  9.12]<br>
>[ 7.87 21.93 10.1  11.85  9.12  6.17]<br>
>[21.93 10.1  11.85  9.12  6.17 -0.43]<br>

<br>
You can see that<br>

>sub0[N] is numarray[N]<br>
>sub1[N] is numarray[N+1]<br>
>sub2[N] is numarray[N+2]<br>
>sub3[N] is numarray[N+3]<br>
>sub4[N] is numarray[N+4]<br>

<br>
<br>

Next, create a numpy-array called ```SUM``` and initialize with sub0+sub1+sub2+sub3+sub4.

Print the first 6 elements in the SUM.

It must be
>[38.8  45.69 52.21 60.87 59.17 36.81]

<br>

```SUM[N]``` must be equal to ```sub0[N]+sub1[N]+sub2[N]+sub3[N]+sub4[N]```, which is equal to ```numarray[N]+numarray[N+1]+numarray[N+2]+numarray[N+3]+numarray[N+4]```.
<br>
<br>
<br>
Next, create a numpy-array called ```MovingAverage``` and initialize with SUM/5.<br>

Print first 6 elements in ```MovingAverage```

It must be
>[ 7.76   9.138 10.442 12.174 11.834  7.362]

<br>

```MovingAverage[N]``` must be equal to the average of ```numarray[N]``` , ```numarray[N+1]```, ```numarray[N+2]```, ```numarray[N+3]```, ```numarray[N+4]```.
<br>
The avarage of ```numarray[N]``` , ```numarray[N+1]```, ```numarray[N+2]```, ```numarray[N+3]```, ```numarray[N+4]``` is called the "moving average of numarray".<br>
By calculating moving average, you can smooth out the spike-noize.
<br>
<br>
Let's see what can be seen from MovingAverage. We may find some signal from it!<br>
>Create a figure whose size is 8 in width and 8 in height.<br>
Create two axes(ax1, and ax2) inside figure. They are placed vertically inside the figure<br>

>Draw line-graph about numarray to the ax1.<br>
Set the label of x-axis to "time[ms]".<br>
Set the label of y-axis to "voltage[mV]".<br>
Set the title of axis to "Raw Data".<br>

>Draw line-graph about MovingAverage to the ax2.<br>
Set the label of x-axis to "time[ms]".<br>
Set the label of y-axis to "voltage[mV]".<br>
Set the title of axis to "Moving Average".<br>

>Set the tile of figure as "Changes of Voltage".

>Finally, show the graph.

You will see 10 spikes in the data!!<br>
Calculating moving average can visualize some signal hidden inside the noise!!